language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - chmod 777 setversion.sh
# command to run tests
script:
  - pytest
  - ./setversion.sh
deploy:
  skip_cleanup: true
  provider: pypi
  on:
    tags: true
    branch:
      - master
      - /(\d+\.)(\d+\.)(\d+)$/
  username: __token__
  password: $PYPI_API_KEY