language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: $PYPI_API_KEY