language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - chmod 777 setversion.sh
# command to run tests
script:
  - pytest
  - ./setversion.sh
deploy:
  skip_cleanup: true
  provider: pypi
  user: "__token__"
    password:
      secure: $PYPI_API_KEY